### ISSUE TITLE
Compact mode

### ISSUE THREAD

**Issue by Yoskutik** [omidnikrah/github-readme-stackoverflow#7]
Could you please add a choice to use your widget without image? Only with amount of reputation and badges.

**Comment by omidnikrah** [comment]
@Yoskutik Yes, Sure. I will add it 🚀

**Comment by omidnikrah** [comment]
@Yoskutik Now you can use compact layout by passing `layout=compact` parameter.

[![Omid Nikrah StackOverflow](https://github-readme-stackoverflow.vercel.app/?userID=6558042&layout=compact&theme=dark)](https://stackoverflow.com/users/6558042/omid-nikrah)
